# This file was generated by GoReleaser. DO NOT EDIT.
class Kable < Formula
  desc "Manage kubernetes resource. GitOps galore!"
  homepage "https://github.com/redradrat/kable"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/redradrat/kable/releases/download/v0.0.4/kable_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "794b967a737c1afc13c8ea51d9ae2cb489c1d5aac37dc8bb6e9f17269b20d184"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/redradrat/kable/releases/download/v0.0.4/kable_0.0.4_Linux_x86_64.tar.gz"
      sha256 "aecca6806832278521aae1667574d0a82e471d3d32cf6fe63a1bcb62aaa57cf3"
    end
  end
  
  depends_on "git"
  depends_on "go-jsonnet"
  depends_on "jsonnet-bundler"

  def install
    bin.install "kable"
  end
end
