# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kable < Formula
  desc "Manage kubernetes resource. GitOps galore!"
  homepage "https://github.com/redradrat/kable"
  version "0.8.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/redradrat/kable/releases/download/v0.8.3/kable_0.8.3_Darwin_arm64.tar.gz"
      sha256 "e012522b0601f6b14abcfa2135a18d08dff2aad7fe819b8eaa76f5c006d58478"

      def install
        bin.install "kable"
        output = Utils.popen_read("#{bin}/kable completion bash")
        (bash_completion/"kable").write output
        output = Utils.popen_read("#{bin}/kable completion zsh")
        (zsh_completion/"_kable").write output
        output = Utils.popen_read("#{bin}/kable completion fish")
        (fish_completion/"kable.fish").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/redradrat/kable/releases/download/v0.8.3/kable_0.8.3_Darwin_x86_64.tar.gz"
      sha256 "72304f30ad6eb2f556b3efbec2d412152d7f11479aeffcd7d19d9342273b557e"

      def install
        bin.install "kable"
        output = Utils.popen_read("#{bin}/kable completion bash")
        (bash_completion/"kable").write output
        output = Utils.popen_read("#{bin}/kable completion zsh")
        (zsh_completion/"_kable").write output
        output = Utils.popen_read("#{bin}/kable completion fish")
        (fish_completion/"kable.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redradrat/kable/releases/download/v0.8.3/kable_0.8.3_Linux_arm64.tar.gz"
      sha256 "3c2da100ca3302dc99044af6da4ace33fc43d0c87b2f58b91dc6cb08d1c4afde"

      def install
        bin.install "kable"
        output = Utils.popen_read("#{bin}/kable completion bash")
        (bash_completion/"kable").write output
        output = Utils.popen_read("#{bin}/kable completion zsh")
        (zsh_completion/"_kable").write output
        output = Utils.popen_read("#{bin}/kable completion fish")
        (fish_completion/"kable.fish").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/redradrat/kable/releases/download/v0.8.3/kable_0.8.3_Linux_x86_64.tar.gz"
      sha256 "1c8f4b5b32d89a7c0fb90cca2a12c156772573beba8d7a107918ff1a5ddadbf9"

      def install
        bin.install "kable"
        output = Utils.popen_read("#{bin}/kable completion bash")
        (bash_completion/"kable").write output
        output = Utils.popen_read("#{bin}/kable completion zsh")
        (zsh_completion/"_kable").write output
        output = Utils.popen_read("#{bin}/kable completion fish")
        (fish_completion/"kable.fish").write output
      end
    end
  end

  depends_on "git"
  depends_on "go-jsonnet"
  depends_on "jsonnet-bundler"
end
