# This file was generated by GoReleaser. DO NOT EDIT.
class Kable < Formula
  desc "Manage kubernetes resource. GitOps galore!"
  homepage "https://github.com/redradrat/kable"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/redradrat/kable/releases/download/v0.6.1/kable_0.6.1_Darwin_x86_64.tar.gz"
    sha256 "8a0b021a58b46652e811bbbe63d93c3bba7a8d48968930e9849cad38bfd9f75b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/redradrat/kable/releases/download/v0.6.1/kable_0.6.1_Linux_x86_64.tar.gz"
      sha256 "0e03fa9b12309223ef314be2b603308c12ba7fc9012e704de02372b02bbb6f85"
    end
  end
  
  depends_on "git"
  depends_on "go-jsonnet"
  depends_on "jsonnet-bundler"

  def install
    bin.install "kable"
  end
end
